# Generated by Django 5.2.15 on 2026-06-09 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="项目名称")),
                ("description", models.TextField(blank=True, verbose_name="项目描述")),
                (
                    "owner",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="项目负责人"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "项目",
                "verbose_name_plural": "项目",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="文档名称")),
                (
                    "version",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="文档版本"
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[("requirement", "需求文档"), ("api", "接口文档")],
                        default="requirement",
                        max_length=20,
                        verbose_name="文档类型",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documents/",
                        verbose_name="文档文件",
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="文档内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="projects.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "需求文档",
                "verbose_name_plural": "需求文档",
                "ordering": ["-created_at"],
            },
        ),
    ]
