# Generated by Django 5.2.15 on 2026-06-09 11:40

import apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="file_ext",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="文件扩展名"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="file_size",
            field=models.PositiveIntegerField(default=0, verbose_name="文件大小(字节)"),
        ),
        migrations.AddField(
            model_name="document",
            name="original_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="原始文件名"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="content",
            field=models.TextField(blank=True, verbose_name="补充说明"),
        ),
        migrations.AlterField(
            model_name="document",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("requirement", "需求文档"),
                    ("api", "接口文档"),
                    ("prd", "PRD文档"),
                    ("prototype", "原型图"),
                    ("other", "其他"),
                ],
                default="requirement",
                max_length=20,
                verbose_name="文档类型",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.projects.models.document_upload_path,
                verbose_name="文档文件",
            ),
        ),
    ]
