# Generated by Django 5.2.15 on 2026-06-09 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_document_file_ext_document_file_size_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChunkUploadSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "upload_id",
                    models.CharField(
                        db_index=True, max_length=64, unique=True, verbose_name="上传ID"
                    ),
                ),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="原始文件名"),
                ),
                ("file_size", models.BigIntegerField(verbose_name="文件大小")),
                ("chunk_size", models.PositiveIntegerField(verbose_name="分片大小")),
                ("total_chunks", models.PositiveIntegerField(verbose_name="总分片数")),
                (
                    "uploaded_chunks",
                    models.JSONField(
                        blank=True, default=list, verbose_name="已上传分片"
                    ),
                ),
                (
                    "form_data",
                    models.JSONField(blank=True, default=dict, verbose_name="表单数据"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "上传中"),
                            ("merging", "合并中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="uploading",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chunk_session",
                        to="projects.document",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunk_uploads",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "分片上传会话",
                "verbose_name_plural": "分片上传会话",
                "ordering": ["-created_at"],
            },
        ),
    ]
