# Generated by Django 5.2.15 on 2026-06-09 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AsyncTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_name",
                    models.CharField(max_length=200, verbose_name="任务名称"),
                ),
                ("task_type", models.CharField(max_length=50, verbose_name="任务类型")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "执行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="执行状态",
                    ),
                ),
                ("result", models.TextField(blank=True, verbose_name="执行结果")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "异步任务",
                "verbose_name_plural": "异步任务",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApiInterface",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="接口名称")),
                (
                    "module",
                    models.CharField(blank=True, max_length=100, verbose_name="模块"),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("DELETE", "DELETE"),
                            ("PATCH", "PATCH"),
                        ],
                        default="GET",
                        max_length=10,
                        verbose_name="请求方式",
                    ),
                ),
                ("url", models.CharField(max_length=500, verbose_name="接口地址")),
                (
                    "headers",
                    models.JSONField(blank=True, default=dict, verbose_name="请求头"),
                ),
                (
                    "params",
                    models.JSONField(blank=True, default=dict, verbose_name="请求参数"),
                ),
                (
                    "body",
                    models.JSONField(blank=True, default=dict, verbose_name="请求体"),
                ),
                ("description", models.TextField(blank=True, verbose_name="接口描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_interfaces",
                        to="projects.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "接口",
                "verbose_name_plural": "接口",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApiTestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="用例标题")),
                (
                    "params",
                    models.JSONField(blank=True, default=dict, verbose_name="请求参数"),
                ),
                (
                    "validate_content",
                    models.TextField(blank=True, verbose_name="校验内容"),
                ),
                (
                    "extract_content",
                    models.JSONField(blank=True, default=dict, verbose_name="提取内容"),
                ),
                (
                    "should_run",
                    models.BooleanField(default=True, verbose_name="是否执行"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="排序"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "api",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="testing.apiinterface",
                        verbose_name="关联接口",
                    ),
                ),
            ],
            options={
                "verbose_name": "接口测试用例",
                "verbose_name_plural": "接口测试用例",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Requirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module",
                    models.CharField(blank=True, max_length=100, verbose_name="模块"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="需求名称")),
                ("description", models.TextField(blank=True, verbose_name="需求描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requirements",
                        to="projects.document",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="projects.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "功能需求",
                "verbose_name_plural": "功能需求",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="测试点名称")),
                (
                    "point_type",
                    models.CharField(
                        choices=[
                            ("functional", "功能测试"),
                            ("boundary", "边界测试"),
                            ("exception", "异常测试"),
                            ("security", "安全测试"),
                        ],
                        default="functional",
                        max_length=20,
                        verbose_name="测试点类型",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_points",
                        to="testing.requirement",
                        verbose_name="关联需求",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试点",
                "verbose_name_plural": "测试点",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="用例标题")),
                ("steps", models.TextField(blank=True, verbose_name="测试步骤")),
                ("expected", models.TextField(blank=True, verbose_name="预期结果")),
                ("actual", models.TextField(blank=True, verbose_name="实际结果")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("P0", "P0-紧急"),
                            ("P1", "P1-高"),
                            ("P2", "P2-中"),
                            ("P3", "P3-低"),
                        ],
                        default="P2",
                        max_length=5,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "executor",
                    models.CharField(blank=True, max_length=100, verbose_name="执行人"),
                ),
                (
                    "passed",
                    models.BooleanField(blank=True, null=True, verbose_name="是否通过"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="排序"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="projects.project",
                        verbose_name="所属项目",
                    ),
                ),
                (
                    "test_point",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="test_cases",
                        to="testing.testpoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试用例",
                "verbose_name_plural": "测试用例",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
