# Generated by Django 5.2.15 on 2026-06-09 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_chunkuploadsession"),
        ("testing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="模板名称")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("login", "登录模板"),
                            ("payment", "支付模板"),
                            ("upload", "文件上传模板"),
                            ("custom", "自定义模板"),
                        ],
                        default="custom",
                        max_length=20,
                        verbose_name="模板分类",
                    ),
                ),
                ("precondition", models.TextField(blank=True, verbose_name="前置条件")),
                ("steps", models.TextField(blank=True, verbose_name="测试步骤")),
                ("expected", models.TextField(blank=True, verbose_name="预期结果")),
                (
                    "postcondition",
                    models.TextField(blank=True, verbose_name="后置条件"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "用例模板",
                "verbose_name_plural": "用例模板",
                "ordering": ["category", "id"],
            },
        ),
        migrations.AlterModelOptions(
            name="requirement",
            options={
                "ordering": ["module", "id"],
                "verbose_name": "功能需求",
                "verbose_name_plural": "功能需求",
            },
        ),
        migrations.AddField(
            model_name="requirement",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="testing.requirement",
            ),
        ),
        migrations.AddField(
            model_name="requirement",
            name="requirement_type",
            field=models.CharField(
                choices=[
                    ("feature", "功能点"),
                    ("constraint", "约束"),
                    ("exception", "异常场景"),
                ],
                default="feature",
                max_length=20,
                verbose_name="需求类型",
            ),
        ),
        migrations.AddField(
            model_name="testcase",
            name="depends_on",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dependents",
                to="testing.testcase",
            ),
        ),
        migrations.AddField(
            model_name="testcase",
            name="postcondition",
            field=models.TextField(blank=True, verbose_name="后置条件"),
        ),
        migrations.AddField(
            model_name="testcase",
            name="precondition",
            field=models.TextField(blank=True, verbose_name="前置条件"),
        ),
        migrations.AddField(
            model_name="testcase",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("manual", "手动用例"),
                    ("ai", "AI用例"),
                    ("test_point", "测试点生成"),
                    ("template", "模板生成"),
                ],
                default="manual",
                max_length=20,
                verbose_name="用例来源",
            ),
        ),
        migrations.AddField(
            model_name="testpoint",
            name="description",
            field=models.TextField(blank=True, verbose_name="测试点描述"),
        ),
        migrations.AddField(
            model_name="testpoint",
            name="design_strategy",
            field=models.CharField(
                choices=[
                    ("equivalence", "等价类"),
                    ("boundary", "边界值"),
                    ("scenario", "场景法"),
                    ("state", "状态迁移"),
                    ("default", "综合策略"),
                ],
                default="default",
                max_length=20,
                verbose_name="设计策略",
            ),
        ),
        migrations.AddField(
            model_name="testpoint",
            name="rag_context",
            field=models.TextField(blank=True, verbose_name="RAG召回上下文"),
        ),
        migrations.AddField(
            model_name="testcase",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="test_cases",
                to="testing.casetemplate",
            ),
        ),
        migrations.CreateModel(
            name="KnowledgeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("experience", "测试经验库"),
                            ("bug", "Bug知识库"),
                            ("history", "历史用例库"),
                        ],
                        default="experience",
                        max_length=20,
                        verbose_name="分类",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="标签"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_items",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识库条目",
                "verbose_name_plural": "知识库条目",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestSuite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="套件名称")),
                (
                    "case_ids",
                    models.JSONField(
                        blank=True, default=list, verbose_name="用例ID列表"
                    ),
                ),
                (
                    "schedule",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="定时任务"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_suites",
                        to="projects.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试套件",
                "verbose_name_plural": "测试套件",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExecutionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="执行名称")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "执行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("partial", "部分成功"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("total", models.PositiveIntegerField(default=0, verbose_name="总数")),
                (
                    "passed",
                    models.PositiveIntegerField(default=0, verbose_name="通过数"),
                ),
                (
                    "failed",
                    models.PositiveIntegerField(default=0, verbose_name="失败数"),
                ),
                (
                    "results",
                    models.JSONField(blank=True, default=list, verbose_name="执行结果"),
                ),
                ("ai_analysis", models.TextField(blank=True, verbose_name="AI分析")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_runs",
                        to="projects.project",
                        verbose_name="所属项目",
                    ),
                ),
                (
                    "suite",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        to="testing.testsuite",
                    ),
                ),
            ],
            options={
                "verbose_name": "执行记录",
                "verbose_name_plural": "执行记录",
                "ordering": ["-created_at"],
            },
        ),
    ]
