# Generated by Django 5.2.15 on 2026-06-10 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_chunkuploadsession"),
        ("testing", "0007_apiinterface_response_example"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiinterface",
            name="dependency_mappings",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='[{"depends_on":1,"source":"body.data.access_token","target":"headers.Authorization"}]',
                verbose_name="关联字段映射",
            ),
        ),
        migrations.CreateModel(
            name="SecurityScanTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_interface_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="来源接口ID"
                    ),
                ),
                (
                    "dependency_mappings",
                    models.JSONField(
                        blank=True, default=list, verbose_name="关联字段映射"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="接口名称")),
                (
                    "module",
                    models.CharField(blank=True, max_length=100, verbose_name="模块"),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("DELETE", "DELETE"),
                            ("PATCH", "PATCH"),
                        ],
                        default="GET",
                        max_length=10,
                        verbose_name="请求方式",
                    ),
                ),
                ("url", models.CharField(max_length=500, verbose_name="接口地址")),
                (
                    "headers",
                    models.JSONField(blank=True, default=dict, verbose_name="请求头"),
                ),
                (
                    "params",
                    models.JSONField(blank=True, default=dict, verbose_name="请求参数"),
                ),
                (
                    "body",
                    models.JSONField(blank=True, default=dict, verbose_name="请求体"),
                ),
                (
                    "response_example",
                    models.JSONField(blank=True, default=dict, verbose_name="响应示例"),
                ),
                ("description", models.TextField(blank=True, verbose_name="接口描述")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="排序"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "depends_on",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dependents",
                        to="testing.securityscantarget",
                        verbose_name="关联扫描目标",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_scan_targets",
                        to="projects.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "安全扫描目标",
                "verbose_name_plural": "安全扫描目标",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
