# Generated by Django 5.2.15 on 2026-06-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="报告名称")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("functional", "功能测试"),
                            ("api", "接口测试"),
                            ("performance", "性能测试"),
                            ("web", "Web自动化"),
                        ],
                        max_length=20,
                        verbose_name="报告类型",
                    ),
                ),
                ("summary", models.TextField(blank=True, verbose_name="报告摘要")),
                ("pass_rate", models.FloatField(default=0, verbose_name="通过率")),
                (
                    "total_cases",
                    models.IntegerField(default=0, verbose_name="总用例数"),
                ),
                ("passed_cases", models.IntegerField(default=0, verbose_name="通过数")),
                (
                    "report_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="报告链接"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "测试报告",
                "verbose_name_plural": "测试报告",
                "ordering": ["-created_at"],
            },
        ),
    ]
