# Generated by Django 5.2.15 on 2026-06-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_features", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIProviderConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="配置名称")),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("zhipu", "智谱 AI"),
                            ("openai", "OpenAI"),
                            ("deepseek", "DeepSeek"),
                            ("qwen", "通义千问"),
                            ("moonshot", "Moonshot"),
                            ("custom", "自定义 OpenAI 兼容"),
                        ],
                        max_length=20,
                        verbose_name="厂商",
                    ),
                ),
                ("api_key", models.CharField(max_length=500, verbose_name="API Key")),
                (
                    "base_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Base URL"
                    ),
                ),
                ("model", models.CharField(max_length=100, verbose_name="模型")),
                ("temperature", models.FloatField(default=0.7, verbose_name="温度")),
                (
                    "max_tokens",
                    models.IntegerField(default=4096, verbose_name="最大 Token"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="当前启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "大模型配置",
                "verbose_name_plural": "大模型配置",
                "ordering": ["-is_active", "-updated_at"],
            },
        ),
    ]
