# Generated by Django 5.2.15 on 2026-06-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_features", "0002_aiproviderconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="AISkillsSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skills_enabled",
                    models.BooleanField(default=True, verbose_name="启用 Skills 注入"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "Skills 全局设置",
                "verbose_name_plural": "Skills 全局设置",
            },
        ),
        migrations.CreateModel(
            name="AISkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="名称")),
                (
                    "folder_name",
                    models.CharField(max_length=200, verbose_name="文件夹名"),
                ),
                ("content", models.TextField(verbose_name="SKILL.md 内容")),
                (
                    "source_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="来源路径"
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("local", "本地扫描"),
                            ("ccswitch", "CC Switch"),
                            ("manual", "手动"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="来源",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True, verbose_name="启用")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
                "ordering": ["sort_order", "name"],
                "unique_together": {("folder_name", "source_path")},
            },
        ),
    ]
